name: patro
description: The revolutionary patro app without Ads.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  clean_nepali_calendar: ^2.0.1

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/2081.json
